name: 'CI/CD'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install JSHint
        run: npm install jshint --global

      - name: Run Linter
        run: |
          find ./giftlink-backend -name "*.js" -exec jshint {} --config <(echo '{ "esversion": 9 }') +
          echo "Linted all JavaScript files successfully"

  client_build:
    name: Build Frontend Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set environment variables
        run: echo "NODE_OPTIONS=--openssl-legacy-provider" >> $GITHUB_ENV

      - name: Install Dependencies
        run: |
          cd giftlink-frontend
          npm install

      - name: Build Frontend
        run: |
          cd giftlink-frontend
          npm run build
          echo "Client-side build completed successfully"
