name: 'CI/CD'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install JSHint
        run: npm install -g jshint

      - name: Run Linter
        run: |
          echo '{ "esversion": 9 }' > .jshintrc  # Create config file dynamically
          find ./giftlink-backend -name "*.js" -exec jshint {} +

  client_build:
    name: Build Frontend Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          cd giftlink-frontend
          npm install

      - name: Set OpenSSL Legacy Mode
        run: echo "NODE_OPTIONS=--openssl-legacy-provider" >> $GITHUB_ENV

      - name: Build Frontend
        run: |
          cd giftlink-frontend
          npm run build
          echo "Client-side build completed successfully"
